---
name: CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [labeled]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  remove-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commit Changes
        run: |
          git checkout -b chore/delete-stack-${{ github.run_id }}
          cd src/stacks
          ls
          rm -rf tata
          git status
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "remove stack"
          git push origin chore/delete-stack-${{ github.run_id }}
