---
name: CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  remove-stack:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commit Changes
        run: |
          cd src/stacks
          ls
          rm -rf tata
          git status
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "remove stack"
          git push -u origin HEAD
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: pr_creation
        with:
          base: main
          title: "chore(${{ github.run_id }}): delete stacks"
          commit-message: "chore(${{ github.run_id }}): delete stacks"
          body: |
            Delete stack
          branch: "chore/delete-stack-${{ github.run_id }}"
          delete-branch: false
          assignees: ${{ github.actor }}
          #token: ${{ steps.generate-token.outputs.token }}
          committer: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>

